### ISSUE TITLE
Command failed mktemp

### ISSUE THREAD

**Issue by naltatis** [StanAngeloff/lotte#1]
I've a problem to get it running on Mac OS X Lion. When I run any `lotte` command i get the following error:

```
$ lotte --verify  
Lotte | ERROR:   Error: Command failed: usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix:

    Error: Command failed: usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
           mktemp [-d] [-q] [-u] -t prefix 

    at ChildProcess.exithandler (child_process.js:102:15)
    at ChildProcess.emit (events.js:67:17)
    at Socket.<anonymous> (child_process.js:172:12)
    at Socket.emit (events.js:64:17)
    at Array.0 (net.js:831:12)
    at EventEmitter._tickCallback (node.js:126:26)
```

Seems like `mktemp` has a problem with how its called!?
When I run it directly without parameters I get the following:

```
$ mktemp          
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
```

I'm running node v0.4.10

naltatis

**Comment by StanAngeloff** [comment]
I just pushed [v0.1.2](http://search.npmjs.org/#/lotte) to npm, can you upgrade and let me know if this fixes it for you?

Relevant commit is [6a08b131](https://github.com/StanAngeloff/lotte/commit/6a08b13148c4d39d8fbb04ac257183d0d67c04d6).

**Comment by naltatis** [comment]
Yes, your change fixed the `mktemp` error. But when i run your github example test, phantomjs starts up (little ghost in dock) and the cpu goes to 100% for a couple of seconds until I get the following error:

```
undefined:852 SyntaxError: Parse error
Lotte | WARNING: Error: Process '87981' terminated with 'SIGTERM', timed out:

    Error: Process '87981' terminated with 'SIGTERM', timed out
        at Object._onTimeout (/usr/local/lib/node_modules/lotte/lib/lotte.js:237:14)
    at Timer.ontimeout (timers.js:84:39)
```

I've tried a simpler test with another domain ...

`this.open('http://www.google.com', function() {});`

... but with the same result (including SyntaxError line number).

**Comment by StanAngeloff** [comment]
OK, try the following snippet, without a `@success()` or `throw '...'` line the test will hang:*

```
this.open('http://www.google.com', function() {
  this.describe('must have at least one test case', function() {
    this.success();
  });
});
```

and you should get:

```
/data/tmp/lotte/lotte_first.js
  @ http://www.google.com
    ✓ must have at least one test case
```

I tried it on a Mac OS X Snow Leopard and it runs correctly. Can you confirm this is the case for you as well?

> *since tests are asynchronous using `@success()` will let Lotte know no jobs are pending and it's safe to finish the test

**Comment by naltatis** [comment]
No, this test doesn't work. I get the same exception as above (using node v0.6.2).

**Comment by StanAngeloff** [comment]
Earlier today I discovered an issue with PhantomJS when not compiled from trunk. I just pushed the update to npm, can you try the example I pasted above with the new `0.1.2-1` please? Let me know how it goes.

**Comment by naltatis** [comment]
now it works. thanks!

**Comment by edwardhotchkiss** [comment]
I'm using lotte latest `v0.1.2-2` and PhantomJS latest on OS X. I've been using Lotte for a while but only get it on this new project ...

**Comment by StanAngeloff** [comment]
Hey @edwardhotchkiss, could you paste the full log, e.g., command-line, output of Lotte, etc.
