### ISSUE TITLE
Setup/teardown (before/after all)

### ISSUE THREAD

**Issue by jgonera** [StanAngeloff/lotte#2]
How about adding a way of executing some code before and after each test? This could be useful to e.g. reset the web app's database contents or the session.

**Comment by StanAngeloff** [comment]
I see how this could be useful, yes. I will have a proper think about how best to integrate this into Lotte, perhaps hooks either via the command-line to execute shell scripts:

```
$ lotte --before-each='./reset.sh'
```

or via `Lottefile`

```
// not tested, just putting ideas in order
path = 'tests'

beforeEach = function(file) {
  if (file.test(/signup/)) {
    require('process').exec('./reset.sh');
  }
}; 
```

**Comment by jgonera** [comment]
I think using `Lottefile` would be better because if someone has a Node app they can use their model directly. But I'm not sure what `file` is in your example.

**Comment by StanAngeloff** [comment]
`file` would ideally contain the test about to be run, e.g., `test_name.coffee` or whatever.

I may look into using both the command-line and `Lottefile`s, certainly there are use cases for both.

**Comment by jgonera** [comment]
I see, looks good to me.

**Comment by StanAngeloff** [comment]
I've added experimental support for events in [00033bec94](https://github.com/StanAngeloff/lotte/commit/00033bec943dc3ddb5563b2b4172d54a0a476192). These events are fired in Node.js so you can use `require('child_process')` to execute a script or even load a module to perform any tasks you may wish to carry.

``` javascript
on('start', function(options, resume) {
  require('child_process').exec('mysql -e "DROP DATABASE development"', function() {
    console.log('Starting fresh, database was dropped.');
    resume();
  });
});
```

**Comment by jgonera** [comment]
So before and after are run before/after each test file, right? Looks good, thanks.

**Comment by StanAngeloff** [comment]
D'oh (slaps forehead)! I should have made events a bit cleared:
- `start` is just before the first test, gives you a chance to fiddle about with the options
- `before`/`after` fire for each test file
- `exit` gives you a chance to sniff the exit code of all test files, e.g., non-zero for fails, zero if all passed

Closing issue, re-open if you have further comments. Ta.
