### ISSUE TITLE
Default filename convention is a bit obscure

### ISSUE THREAD

**Issue by craftgear** [StanAngeloff/lotte#5]
_an explanatory note: This is not a issue._

Hi, I could manage to install and run lotte on npm 1.0.6 and PhantomJS 1.3.0.
(Yes, I compiled both of them from source.)

At first I tried to run the sample 'github' testcase and I couldn't run it.
Because of I named the test file as 'github.js' not 'lotte_github.js'.

Why do I have to name test files with prefix 'lotte'?
Although I know that I can change this behavior with changing Lottefile,
 I think this convention is a bit obscure.
As lotte command says nothing when it couldn't find any test files. 

I hope this will be changed and other people like me feel comfortable to test with lotte.
I really love this project.

Regards.

**Comment by StanAngeloff** [comment]
Lotte is meant to integrate with existing projects. You'd normally place your `Lottefile` in the root of your project. It is very likely you have a directory somewhere which contains assets and scripts, e.g., `jquery.min.js` or `mootools.js`. Lotte should not consider those for testing, therefore it expects the files to have been labelled properly.

I agree, however, just exiting with no message is a bad, bad thing to do. I'd probably look into adding a prompt like:

```
No '**/lotte_*.{coffee,js}' files were found in '/data/projects/XYZ'.
```

**Comment by craftgear** [comment]
I'm glad to hear you'll give a thought of it.

Cheers.

**Comment by StanAngeloff** [comment]
If you don't mind, I'd reopen the issue so it lists on the Issues page, kind of a good reminder I need to get it sorted.
