### ISSUE TITLE
Lotte not compatible with latest phantomjs available to npm

### ISSUE THREAD

**Issue by tomwoods** [StanAngeloff/lotte#7]
c:>npm install -g phantomjs
c:>npm -g install lotte

c:>lotte
Lotte | ERROR:   PhantomJS version '1.9.0' does not meet requirement '~1.3.0 ||
~1.4.0 || ~1.5.0 || ~1.6.0 || ~1.7.0'.

**Comment by tomwoods** [comment]
Available packages in npm:

c:>npm view phantomjs versions

[ '0.0.1',
  '0.0.2',
  '0.0.3',
  '0.0.4',
  '0.0.5',
  '0.0.6',
  '0.0.7',
  '0.0.8',
  '0.0.9',
  '0.1.0',
  '0.1.1',
  '0.2.0',
  '0.2.1',
  '0.2.2',
  '0.2.3',
  '0.2.4',
  '0.2.5',
  '0.2.6',
  '1.8.0-1',
  '1.8.1-1',
  '1.8.1-2',
  '1.8.1-3',
  '1.8.2-0',
  '1.8.2-1',
  '1.8.2-2',
  '1.9.0-0' ]

that is, it seems like lotte isn't compatible with any version of phantomjs available via npm

**Comment by StanAngeloff** [comment]
Thanks for the report, I'll test and update with 1.9.x tomorrow. You can use `--no-verify` on the command-line to skip version checks as a workaround.

**Comment by StanAngeloff** [comment]
Lotte should work with `1.9.x` after a [series of commits](https://github.com/StanAngeloff/lotte/compare/53aa973dbf...24f87df30a) earlier today. Please note you must have a `phantomjs` executable on your `$PATH`. I am not sure now `npm install -g phantomjs` behaves.
