### ISSUE TITLE
Lotte seems to require phantomjs in path

### ISSUE THREAD

**Issue by jlink** [StanAngeloff/lotte#9]
Lotte seems to require that phantomjs binary is available in PATH. Why not get the path to the phantomjs library from location.js in the phantomjs nodes module? This would enable the use of Lotte when phantomjs has not been installed globally.

**Comment by StanAngeloff** [comment]
You can use the `--phantom` flag (or `phantom` variable in `Lottefile`) to set up a custom path to the `phantom` binary. Does that help?

Lotte does not use PhantomJS as a node module so there may be no `location.js` file.

**Comment by jlink** [comment]
Setting phantom property in Lottefile should work (cannot try it right now), I wasn't aware of that.

For a future release you might consider Lotte to have "phantom" as an (optional) peer dependency which would make the setup even easier for node users.
